import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { hostname, userInfo } from 'node:os';
import path from 'node:path';
import { logWarn } from './log';
import { CONFIG_DIR } from './paths';

const IS_WINDOWS = process.platform === 'win32';

// Generate a bash rcfile that gives a fish-like prompt: cwd abbreviated to
// first letters (~/S/p/t/a/server), git branch, and a ❯ char. Written to a file
// (not an inlined PS1) so the shell logic stays readable.
// bashrc + holder sockets live alongside the DB (CONFIG_DIR already resolves
// env / installed-binary / dev-source to the right place — see paths.ts).
const RC_DIR = CONFIG_DIR;
const RC_PATH = path.join(RC_DIR, 'tether.bashrc');
const BASHRC = [
  '[ -f ~/.bashrc ] && source ~/.bashrc',
  '_tether_pwd() {',
  '  local tilde="~" p out="" seg i=0 n',
  '  p="${PWD/#$HOME/$tilde}"', // via var so ~ is not re-expanded back to $HOME
  '  local -a parts',
  '  IFS=/ read -ra parts <<< "$p"',
  '  n=${#parts[@]}',
  '  for seg in "${parts[@]}"; do',
  '    i=$((i+1))',
  '    if [ $i -lt $n ] && [ -n "$seg" ]; then',
  '      if [[ $seg == .* ]]; then out+="${seg:0:2}"; else out+="${seg:0:1}"; fi',
  '    else',
  '      out+="$seg"',
  '    fi',
  '    [ $i -lt $n ] && out+="/"',
  '  done',
  '  printf "%s" "$out"',
  '}',
  '_tether_branch() { local b; b=$(git branch --show-current 2>/dev/null); [ -n "$b" ] && printf " (%s)" "$b"; }',
  '_tether_osc7() { printf "\\e]7;file://%s%s\\a" "$(hostname)" "$PWD"; }',
  "PS1='\\[$(_tether_osc7)\\]\\[\\e[36m\\]$(_tether_pwd)\\[\\e[0m\\]\\[\\e[33m\\]$(_tether_branch)\\[\\e[0m\\] \\[\\e[32m\\]❯\\[\\e[0m\\] '",
  '',
].join('\n');
mkdirSync(RC_DIR, { recursive: true, mode: 0o700 });
// Tighten an existing dir too — the config dir holds the argon2 hash and the
// holder IPC sockets, so no other local user should be able to traverse it.
try {
  chmodSync(RC_DIR, 0o700);
} catch {}
writeFileSync(RC_PATH, BASHRC);

// zsh has no --rcfile-equivalent flag for interactive mode; the standard,
// safe (zsh-only, unlike XDG_CONFIG_HOME) redirect is the ZDOTDIR env var,
// which zsh reads $ZDOTDIR/.zshrc from instead of ~/.zshrc. Only the invisible
// OSC 7 hook is added — no prompt replacement, since zsh users already have
// their own (bare `~/.zshrc`, not `$ZDOTDIR`-relative, so a customized
// ZDOTDIR of the user's own is intentionally not chased here — same
// simplification the bash rcfile already makes for ~/.bashrc).
const ZSH_RC_DIR = path.join(RC_DIR, 'zsh');
const ZSHRC = [
  '[ -f ~/.zshrc ] && source ~/.zshrc',
  '_tether_osc7() { printf "\\e]7;file://%s%s\\a" "$(hostname)" "$PWD"; }',
  'precmd_functions+=(_tether_osc7)',
  '',
].join('\n');
// ZDOTDIR redirects ALL of zsh's startup files, not just .zshrc — .zshenv is
// read even for non-interactive shells and is the canonical place users put
// PATH/SDK-manager/Nix env setup (zsh does not fall back to ~/.zshenv once
// ZDOTDIR is set, so without this that setup would silently vanish).
const ZSHENV = '[ -f ~/.zshenv ] && source ~/.zshenv\n';
mkdirSync(ZSH_RC_DIR, { recursive: true });
writeFileSync(path.join(ZSH_RC_DIR, '.zshrc'), ZSHRC);
writeFileSync(path.join(ZSH_RC_DIR, '.zshenv'), ZSHENV);

// fish has no rcfile-redirect env var without risking collateral effects on
// other XDG-aware tools in the session (XDG_CONFIG_HOME would redirect ALL of
// them, not just fish) — --init-command runs before fish's own config.fish,
// with no environment side effects at all.
const FISH_INIT =
  'function _tether_osc7 --on-event fish_prompt; printf "\\e]7;file://%s%s\\a" (hostname) (pwd); end';

// PowerShell's equivalent of the bash rcfile. `-File` still runs the user's
// profiles first (only -NoProfile skips them), so this lands on top of their
// setup exactly the way BASHRC sources ~/.bashrc before setting PS1. Paired
// with -NoExit so the shell stays interactive after the script returns.
//
// The OSC 7 payload uses forward slashes ("file://host/C:/Users/x") because a
// file URI has no other legal separator; liveCwd.ts turns that back into a
// native "C:\Users\x" — see normalizeOsc7Cwd there.
const PS_RC_PATH = path.join(RC_DIR, 'tether.profile.ps1');
const PS_PROFILE = [
  '# Generated by tether — shell integration (OSC 7 cwd reporting + prompt).',
  '$ErrorActionPreference = "Continue"',
  // The prompt below draws a ❯; without this ConPTY renders it as mojibake
  // under a non-UTF-8 console codepage (the default on many fr/de installs).
  'try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}',
  'function global:_TetherPwd {',
  '  $p = $ExecutionContext.SessionState.Path.CurrentLocation.ProviderPath',
  '  if ($HOME -and $p.StartsWith($HOME, [System.StringComparison]::OrdinalIgnoreCase)) {',
  '    $p = "~" + $p.Substring($HOME.Length)',
  '  }',
  '  $parts = $p -split "[\\\\/]"',
  '  $n = $parts.Count',
  '  $out = ""',
  '  for ($i = 0; $i -lt $n; $i++) {',
  '    $seg = $parts[$i]',
  '    if ($i -lt ($n - 1) -and $seg) {',
  '      if ($seg.StartsWith(".")) { $out += $seg.Substring(0, [Math]::Min(2, $seg.Length)) }',
  '      else { $out += $seg.Substring(0, 1) }',
  '    } else { $out += $seg }',
  '    if ($i -lt ($n - 1)) { $out += "/" }',
  '  }',
  '  return $out',
  '}',
  'function global:_TetherBranch {',
  '  $b = (git branch --show-current 2>$null)',
  '  if ($b) { return " ($b)" }',
  '  return ""',
  '}',
  'function global:prompt {',
  '  $e = [char]27',
  '  $full = $ExecutionContext.SessionState.Path.CurrentLocation.ProviderPath',
  // Only filesystem locations get an OSC 7 — a PSDrive like HKLM: or Cert: is
  // not a directory and would poison the git/file features with a bogus cwd.
  '  if ($full -and $full -match "^[A-Za-z]:") {',
  '    $uri = "file://" + [System.Net.Dns]::GetHostName() + "/" + ($full -replace "\\\\", "/")',
  '    $host.UI.Write("$e]7;$uri" + [char]7)',
  '  }',
  '  "$e[36m$(_TetherPwd)$e[0m$e[33m$(_TetherBranch)$e[0m $e[32m❯$e[0m "',
  '}',
  '',
].join('\n');
// Written WITH a UTF-8 BOM, which is load-bearing rather than decoration.
//
// Windows PowerShell 5.1 — the in-box fallback whenever pwsh 7 is not installed
// (getDefaultWindowsShell prefers pwsh, but does not require it) — decodes a
// BOM-less .ps1 using the system ANSI code page, not UTF-8. This file contains
// non-ASCII in both the prompt glyph (❯) and its own comments (—), so on any
// non-UTF-8 console default, which is most fr/de installs, the script is
// already corrupted at PARSE time. The `[Console]::OutputEncoding = UTF8` line
// inside it cannot help: by the time it runs, the mojibake is baked into the
// string literal it was meant to protect. A BOM makes 5.1 decode the file as
// UTF-8, and pwsh 7 — which assumes UTF-8 anyway — honours it too.
// Built from the code point rather than pasted as a character: U+FEFF is
// invisible in an editor, so a literal one here could be dropped or duplicated
// by anyone touching this line without them ever seeing it.
const UTF8_BOM = String.fromCharCode(0xfeff);
if (IS_WINDOWS) writeFileSync(PS_RC_PATH, `${UTF8_BOM}${PS_PROFILE}`);

// cmd.exe has no rcfile at all; its only hook is the PROMPT string, which does
// understand $E (ESC) and $P (cwd). $P expands to a native "C:\dir" path, so
// unlike every other shell here the URI carries backslashes — normalizeOsc7Cwd
// accepts both. The hostname is baked in because cmd does not expand %VAR%
// inside PROMPT at print time.
const CMD_PROMPT = `$E]7;file://${hostname()}/$P$E\\$P$G `;

export interface ShellInvocation {
  args: string[];
  env?: Record<string, string>;
}

// Picks the spawn args (and any env override) that wire up shell integration
// (currently just OSC 7 cwd tracking) for the given command, per-shell since
// each needs a different injection mechanism — bash's --rcfile, zsh's ZDOTDIR
// redirect, fish's --init-command. Anything else runs as-is (matches the
// pre-existing fallback: no shell integration attempted).
export function shellInvocation(command: string): ShellInvocation {
  warnAboutShell(command);
  // Dispatch matches on basename, but argv[0] keeps the original (possibly
  // absolute, e.g. /opt/homebrew/bin/fish) command — the daemon's own PATH may
  // not include the shell's install directory even when the resolved login
  // shell (getDefaultShell(), read from /etc/passwd) does exist at that path.
  const shell = path.basename(command);
  if (shell === 'bash') return { args: [command, '--rcfile', RC_PATH, '-i'] };
  if (shell === 'zsh') return { args: [command, '-i'], env: { ZDOTDIR: ZSH_RC_DIR } };
  if (shell === 'fish') return { args: [command, '--init-command', FISH_INIT, '-i'] };
  // Windows shells are matched with the extension optional and case-insensitively
  // — a user-configured defaultShell may be "pwsh", "pwsh.exe" or a full
  // "C:\Program Files\PowerShell\7\pwsh.exe", and NTFS does not care about case.
  const win = shell.toLowerCase().replace(/\.exe$/, '');
  if (win === 'pwsh' || win === 'powershell') {
    return { args: [command, '-NoLogo', '-NoExit', '-File', PS_RC_PATH] };
  }
  // /K keeps cmd interactive after running the (empty) command; PROMPT is
  // inherited from the env we hand the holder.
  if (win === 'cmd') return { args: [command, '/K'], env: { PROMPT: CMD_PROMPT } };
  // No `-i` on Windows: it is a POSIX-shell convention and cmd/powershell treat
  // it as a file argument, which makes the shell exit immediately.
  if (IS_WINDOWS) return { args: [command] };
  return { args: [command, '-i'] };
}

export function getDefaultShell(): string {
  if (IS_WINDOWS) return getDefaultWindowsShell();
  try {
    const username = userInfo().username;
    const passwd = readFileSync('/etc/passwd', 'utf8');
    for (const line of passwd.split('\n')) {
      const parts = line.split(':');
      if (parts[0] === username && parts[6]) {
        return parts[6];
      }
    }
  } catch {}
  return process.env.SHELL || 'bash';
}

// Windows has no /etc/passwd and no per-user login shell. Prefer PowerShell 7
// (pwsh) over the in-box Windows PowerShell 5.1, and fall back to ComSpec.
// SHELL is deliberately NOT consulted: Git for Windows sets it to its bundled
// bash.exe for every process it launches, which would silently make an MSYS
// shell — with MSYS paths the git/file features cannot resolve — the default
// for anyone who started the daemon from a Git Bash prompt.
function getDefaultWindowsShell(): string {
  for (const candidate of ['pwsh.exe', 'powershell.exe']) {
    if (Bun.which(candidate)) return candidate;
  }
  return process.env.ComSpec || 'cmd.exe';
}

// How much of tether's shell integration a given command actually gets:
//
//   'full'   — OSC 7 cwd reporting is injected (see shellInvocation above), so
//              the git diff, workspace file tree and live-cwd features follow
//              the shell around.
//   'none'   — the shell runs, output streams, keys work; nothing else is
//              wired up. sh, tcsh, a bare command. Perfectly usable.
//   'broken' — the shell runs and then quietly reports paths no Windows API can
//              resolve, so the features above point at nothing. Only reachable
//              on Windows, and only for MSYS/Cygwin-family shells.
export type ShellIntegration = 'full' | 'none' | 'broken';

export interface ShellSupport {
  /** The normalized shell name the classification was made on ('bash', 'pwsh'…). */
  shell: string;
  integration: ShellIntegration;
  /** Why, in one sentence a client can show verbatim. Null when 'full'. */
  reason: string | null;
}

// getDefaultWindowsShell() refuses to read $SHELL because Git for Windows sets
// it to its own bash.exe, and an MSYS bash reports "/c/Users/..." — a path
// findGitRoot, the workspace tree and every upload target fail to resolve. But
// session.defaultShell is client-editable through PATCH /api/config, so that
// defence only ever covered the default: a user could type "bash.exe" in the
// client and land in exactly the same silent breakage.
//
// Which family a Windows bash belongs to is only ever a hint (Git for Windows,
// MSYS2 and Cygwin all install to conventional but not guaranteed locations),
// so the *classification* does not depend on it — every bash/sh-family shell on
// Windows is treated as broken, because all of them emulate POSIX paths. The
// install directory is used solely to name the culprit in the message, which is
// what makes the warning actionable.
const MSYS_FLAVOURS: [RegExp, string][] = [
  [/[\\/]git[\\/]/i, 'Git for Windows'],
  [/[\\/]msys\d*[\\/]/i, 'MSYS2'],
  [/[\\/]cygwin\d*[\\/]/i, 'Cygwin'],
  [/[\\/]system32[\\/]/i, 'WSL'],
];
const POSIX_SHELLS = new Set(['bash', 'sh', 'dash', 'ksh', 'ash', 'zsh', 'fish']);
/** The shells shellInvocation() has an integration hook for, per platform. */
const INTEGRATED_WINDOWS = new Set(['pwsh', 'powershell', 'cmd']);
const INTEGRATED_POSIX = new Set(['bash', 'zsh', 'fish']);

/** Basename, lowercased, with Windows' optional .exe removed. */
function shellName(command: string, isWindows: boolean): string {
  const base = isWindows ? path.win32.basename(command) : path.posix.basename(command);
  return isWindows ? base.toLowerCase().replace(/\.exe$/, '') : base;
}

/**
 * Classifies a shell command, without running it or touching the filesystem.
 *
 * Takes the platform explicitly — the same trick normalizeOsc7Cwd uses in
 * liveCwd.ts — so the Windows rules stay testable from a POSIX CI runner.
 */
export function describeShellSupport(
  command: string,
  isWindows = process.platform === 'win32',
): ShellSupport {
  const shell = shellName(command, isWindows);
  const integrated = isWindows ? INTEGRATED_WINDOWS : INTEGRATED_POSIX;
  if (integrated.has(shell)) return { shell, integration: 'full', reason: null };
  if (isWindows && POSIX_SHELLS.has(shell)) {
    const flavour = MSYS_FLAVOURS.find(([re]) => re.test(command))?.[1];
    return {
      shell,
      integration: 'broken',
      reason:
        `${shell}${flavour ? ` from ${flavour}` : ''} reports POSIX paths like ` +
        '/c/Users/you, which no Windows API can resolve, so the git diff, file tree and ' +
        'upload features will not work in this session. Use pwsh, powershell or cmd instead.',
    };
  }
  return {
    shell,
    integration: 'none',
    reason:
      `tether has no cwd-reporting hook for ${shell}, so the git and file views ` +
      "stay on the session's starting directory. Everything else works.",
  };
}

// Warned once per distinct command rather than once per session: a user who
// deliberately keeps an MSYS shell should not have the daemon log grow a line
// every time they open a tab, and the message says nothing new the second time.
const warnedShells = new Set<string>();

function warnAboutShell(command: string): void {
  if (warnedShells.has(command)) return;
  warnedShells.add(command);
  const support = describeShellSupport(command);
  // Only 'broken' is worth a line. 'none' is the documented fallback for every
  // shell tether has no hook for, and saying so would be noise.
  if (support.integration !== 'broken') return;
  logWarn(`Session shell "${command}" has broken tether integration: ${support.reason}`);
}
