import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const root = path.resolve(import.meta.dir, '..');
const outdir = await mkdtemp(path.join(tmpdir(), 'tether-terminal-renderer-'));
const result = await Bun.build({
  entrypoints: [path.join(root, 'terminal-renderer/index.ts')],
  outdir,
  target: 'browser',
  format: 'iife',
  minify: true,
});

try {
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    process.exitCode = 1;
  } else {
    const jsOutput = result.outputs.find((output) => output.path.endsWith('.js'));
    const cssOutput = result.outputs.find((output) => output.path.endsWith('.css'));
    if (!jsOutput) throw new Error('terminal renderer build produced no JavaScript');

    const js = (await readFile(jsOutput.path, 'utf8')).replaceAll('</script', '<\\/script');
    const css = cssOutput ? await readFile(cssOutput.path, 'utf8') : '';
    const generated = `// Generated by bun run build:terminal-renderer. Do not edit.\nexport const TERMINAL_RENDERER_BUNDLE = ${JSON.stringify(js)};\nexport const TERMINAL_RENDERER_CSS = ${JSON.stringify(css)};\n`;
    await writeFile(path.join(root, 'src/terminalRenderer.generated.ts'), generated);
  }
} finally {
  await rm(outdir, { recursive: true, force: true });
}
