import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const root = path.resolve(import.meta.dir, '..');
const outdir = await mkdtemp(path.join(tmpdir(), 'tether-terminal-renderer-'));
const result = await Bun.build({
  entrypoints: [path.join(root, 'terminal-renderer/index.ts')],
  outdir,
  target: 'browser',
  format: 'iife',
  minify: true,
});

try {
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    process.exitCode = 1;
  } else {
    const jsOutput = result.outputs.find((output) => output.path.endsWith('.js'));
    const cssOutput = result.outputs.find((output) => output.path.endsWith('.css'));
    if (!jsOutput) throw new Error('terminal renderer build produced no JavaScript');

    const js = (await readFile(jsOutput.path, 'utf8')).replaceAll('</script', '<\\/script');
    const css = cssOutput ? await readFile(cssOutput.path, 'utf8') : '';
    const generated = `// Generated by bun run build:terminal-renderer. Do not edit.\nexport const TERMINAL_RENDERER_BUNDLE = ${JSON.stringify(js)};\nexport const TERMINAL_RENDERER_CSS = ${JSON.stringify(css)};\n`;
    await writeFile(path.join(root, 'src/terminalRenderer.generated.ts'), generated);

    // The renderer runs inside a WebView, which cannot see fonts the RN app has
    // bundled — that is why the font picker used to be desktop-only and mobile
    // was pinned to system mono. Inline the same TTFs the app registers, as
    // @font-face data URIs, under the exact family names the app passes in the
    // hydrate command. Costs a few hundred KB in the page; the alternative is
    // fetching them over the network, which the page has no authenticated way
    // to do.
    const fontFace = async (family: string, file: string) => {
      const ttf = await readFile(path.join(root, 'node_modules/@expo-google-fonts', file));
      return `@font-face{font-family:"${family}";font-style:normal;font-weight:400;src:url(data:font/ttf;base64,${ttf.toString('base64')}) format("truetype")}`;
    };
    const fonts = [
      await fontFace('FiraCode_400Regular', 'fira-code/400Regular/FiraCode_400Regular.ttf'),
      await fontFace(
        'JetBrainsMono_400Regular',
        'jetbrains-mono/400Regular/JetBrainsMono_400Regular.ttf',
      ),
    ].join('\n');
    await writeFile(
      path.join(root, 'src/terminalFonts.generated.ts'),
      `// Generated by bun run build:terminal-renderer. Do not edit.\nexport const TERMINAL_RENDERER_FONTS = ${JSON.stringify(fonts)};\n`,
    );
  }
} finally {
  await rm(outdir, { recursive: true, force: true });
}
